# Generated by Django 4.2.5 on 2023-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_user_date_of_birth_appoinment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Patient', 'Patient')], max_length=10, null=True),
        ),
    ]
