# Generated by Django 4.2.5 on 2023-10-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
