# Generated by Django 4.2.5 on 2023-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
