# Generated by Django 4.2.5 on 2023-11-04 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0008_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
    ]
