# Generated by Django 4.2.5 on 2023-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0010_appoinment_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("distance", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
