# Generated by Django 4.2.5 on 2023-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0015_rename_created_at_payment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
