# Generated by Django 4.2.5 on 2023-11-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0017_appoinment_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appoinment",
            name="object_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
