# Generated by Django 4.2.5 on 2023-11-18 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0019_razorpayinvoice_remove_payment_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="razorpayinvoice",
            name="receipt",
        ),
    ]
