# Generated by Django 4.2.5 on 2023-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0020_remove_razorpayinvoice_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
        migrations.AddField(
            model_name="appoinment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="RazorPayInvoice",
        ),
    ]
