# Generated by Django 4.2.5 on 2023-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0021_remove_payment_invoice_appoinment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
