# Generated by Django 4.2.5 on 2024-01-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0026_rename_results_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="appointment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="appoinment",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appoinment_report",
                to="tests.report",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="appoinment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_appoinments",
                to="tests.appoinment",
            ),
        ),
    ]
