# Generated by Django 4.2.5 on 2024-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0028_rename_appointment_status_appoinment_appoinment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appoinment",
            old_name="appoinment_status",
            new_name="appointment_status",
        ),
    ]
