# Generated by Django 4.2.5 on 2024-02-10 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0032_remove_cartitem_amount_order_cartitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="is_available",
        ),
    ]
