# Generated by Django 4.2.5 on 2024-02-10 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0033_remove_cartitem_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_sale_price",
        ),
    ]
