# Generated by Django 4.2.5 on 2024-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0034_remove_product_product_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
