# Generated by Django 4.2.5 on 2024-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0037_order_razorpay_order_id_payment_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
