# Generated by Django 4.2.5 on 2024-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0038_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
