# Generated by Django 4.2.5 on 2024-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0039_alter_location_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
