# Generated by Django 4.2.5 on 2024-02-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0040_alter_location_distance_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="tests.location",
            ),
        ),
    ]
