# Generated by Django 4.2.5 on 2024-03-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0041_order_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deliveryboy",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a delivery boy.",
                verbose_name="Delivery Boy Status",
            ),
        ),
    ]
