# Generated by Django 4.2.5 on 2024-03-13 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0044_alter_deliverystatus_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryStatus",
        ),
    ]
