# Generated by Django 4.2.5 on 2024-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0045_delete_deliverystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
