# Generated by Django 4.2.5 on 2024-03-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0046_order_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_by_delivery_boy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
