# Generated by Django 4.2.5 on 2024-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0047_order_updated_by_delivery_boy"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
