# Generated by Django 4.2.5 on 2024-03-14 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0048_order_delivered_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
