# Generated by Django 4.2.5 on 2024-03-14 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0049_alter_order_delivered_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivered_date",
        ),
    ]
